# Setup
title:               Lucas F. Jones
tagline:             ''
description:         ''
url:                 https://LucasFJones.github.io
baseurl:             'LucasFJones'
paginate:            5
permalink:           Posts/

# About/contact
author:
  name:              Lucas F. Jones
  url:               https://github.com/LucasFJones
  email:             lucas.jones@uconn.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
